services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.111.0
    container_name: otel-col
    restart: unless-stopped
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./otel/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"  # OTLP over gRPC receiver
      - "4318:4318"  # OTLP over HTTP receiver
      - "8888:8888"  # Collector internal metrics endpoint
    depends_on:
      clickhouse:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "9000:9000"  # native protocol
      - "8123:8123"  # HTTP interface
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    depends_on:
      clickhouse:
        condition: service_healthy

  goapp:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - otelcol

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  clickhouse-data:
  db-data:
